--PRESIDENTS
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (5, 'James Monroe', 1817, 1825, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (6, 'John Quincy Adams', 1825, 1829, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (7, 'Andrew Jackson', 1829, 1837, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (8, 'Martin Van Buren', 1837, 1841, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (9, 'William Henry Harrison', 1841, 1841, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (10, 'John Tyler', 1841, 1845, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (11, 'James K. Polk', 1845, 1849, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (12, 'Zachary Taylor', 1849, 1850, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (13, 'Millard Fillmore', 1850, 1853, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (14, 'Franklin Pierce', 1853, 1857, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (15, 'James Buchanan', 1857, 1861, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (16, 'Abraham Lincoln', 1861, 1865, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (17, 'Andrew Johnson', 1865, 1869, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (18, 'Ulysses S. Grant', 1869, 1877, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (19, 'Rutherford B. Hayes', 1877, 1881, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (20, 'James A. Garfield', 1881, 1881, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (21, 'Chester A. Arthur', 1881, 1885, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (22, 'Grover Cleveland', 1885, 1889, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (23, 'Benjamin Harrison', 1889, 1893, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (24, 'Grover Cleveland', 1893, 1897, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (25, 'William McKinley', 1897, 1901, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (26, 'Theodore Roosevelt', 1901, 1909, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (27, 'William Howard Taft', 1909, 1913, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (28, 'Woodrow Wilson', 1913, 1921, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (29, 'Warren G. Harding', 1921, 1923, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (30, 'Calvin Coolidge', 1923, 1929, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (31, 'Herbert Hoover', 1929, 1933, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (32, 'Franklin D. Roosevelt', 1933, 1945, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (33, 'Harry S. Truman', 1945, 1953, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (34, 'Dwight D. Eisenhower', 1953, 1961, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (35, 'John F. Kennedy', 1961, 1963, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (36, 'Lyndon B. Johnson', 1963, 1969, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (37, 'Richard Nixon', 1969, 1974, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (38, 'Gerald Ford', 1974, 1977, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (39, 'Jimmy Carter', 1977, 1981, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (40, 'Ronald Reagan', 1981, 1989, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (41, 'George H. W. Bush', 1989, 1993, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (42, 'Bill Clinton', 1993, 2001, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (43, 'George W. Bush', 2001, 2009, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (44, 'Barack Obama', 2009, 2017, true);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (45, 'Donald Trump', 2017, 2021, false);
INSERT INTO president (chronologicalNumber, fullName, startYear, endYear, hadPets) VALUES (46, 'Joe Biden', 2021, NULL, true);



INSERT INTO pet (fullName, species, presidentID) VALUES ('Drunkard', 'dog', 1);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Taster', 'dog', 1);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Tippler', 'dog', 1);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Sweet Lips', 'dog', 1);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Vulcan', 'dog', 4);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Captain', 'horse', 4);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Satan', 'horse', 4);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Junot', 'horse', 4);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Old Whitey', 'horse', 9);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Le Beau', 'horse', 10);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Polly', 'parrot', 11);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Fido', 'dog', 16);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Old Ike', 'ram', 18);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Punch', 'dog', 23);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Judy', 'dog', 23);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Mr. Reciprocity', 'possum', 24);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Mr. Protection', 'possum', 24);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Emily Spinach', 'snake', 26);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Pauline Wayne', 'cow', 27);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Pete', 'rabbit', 28);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Laddie Boy', 'dog', 29);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Rebecca', 'raccoon', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Ebeneezer', 'donkey', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Bessie', 'cow', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Tiny Tim', 'dog', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Blackberry', 'dog', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Ruby Rouch', 'dog', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Boston Beans', 'dog', 30);
INSERT INTO pet (fullName, species, presidentID) VALUES ('King Tut', 'dog', 31);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Fala', 'dog', 32);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Pushinka', 'dog', 35);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Charlie', 'dog', 35);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Him and Her', 'dogs', 36);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Checkers', 'dog', 37);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Edgar', 'dog', 37);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Pasha', 'dog', 37);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Vicky', 'dog', 37);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Liberty', 'dog', 38);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Grits', 'dog', 39);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Misty Malarky Ying Yang', 'cat', 39);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Rex', 'dog', 40);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Lucky', 'dog', 40);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Millie', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Victory', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Ranger', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Willie', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Ernie', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Freckles', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Pierre', 'dog', 41);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Buddy', 'dog', 42);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Socks', 'cat', 42);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Barney', 'dog', 43);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Miss Beazley', 'dog', 43);
INSERT INTO pet (fullName, species, presidentID) VALUES ('India', 'cat', 43);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Spot', 'dog', 43);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Bo', 'dog', 44);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Sunny', 'dog', 44);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Major', 'dog', 46);
INSERT INTO pet (fullName, species, presidentID) VALUES ('Champ', 'dog', 46);